### ISSUE TITLE
Try catch error when 2 servers are the same port

### ISSUE THREAD

**Issue by gianarb** [gianarb/lb#25]
**Steps to reproduce the issue:**
1. Add 2 servers on the same port

**Describe the results you received:**

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x36fb9]

goroutine 25 [running]:
runtime.panic(0x227760, 0x393b64)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xc5
github.com/gianarb/lb/proxy.StartFrontend(0x1110ffef, 0x6, 0x1117c080, 0x0, 0x0)
        /Users/gianarb/go/src/github.com/gianarb/lb/proxy/manager.go:15 +0x359
created by github.com/gianarb/lb/api.func·003
        /Users/gianarb/go/src/github.com/gianarb/lb/api/frontend.go:41 +0x209

goroutine 16 [semacquire]:
sync.runtime_Semacquire(0x11134660)
        /usr/local/go/src/pkg/runtime/sema.goc:199 +0x31
sync.(*WaitGroup).Wait(0x1110eb00)
        /usr/local/go/src/pkg/sync/waitgroup.go:129 +0x127
main.main()
        /Users/gianarb/go/src/github.com/gianarb/lb/main.go:41 +0x3f4
```

And server down

**Describe the results you expected:**
Server up and an error message friendly

**Comment by gianarb** [comment]
Reference #17
